export const attributes = {
  main: ["năng lực chính", "nhanh nhẹn", "sức mạnh", "trí tuệ", "ý chí"],
  sub: [
    "công phép",
    "hiệu quả điều trị",
    "hp",
    "nhận tuyệt kỹ",
    "st băng",
    "st điện",
    "st nhiệt",
    "st thuật pháp",
    "st tự nhiên",
    "st vật lý",
    "tấn công",
    "tỷ lệ bạo kích",
  ],

  skill: [
    "áp chế",
    "cảm hứng",
    "chạng vạng",
    "chữa lành",
    "đột kích",
    "hiếu chiến",
    "hiệu lực",
    "kích nổ",
    "nghiền",
    "nhiễm",
    "rạn nứt",
    "tàn bạo",
    "truy kích",
    "uyển chuyển",
  ],
};
